### ISSUE TITLE
Works great in X11, any idea how to make it work with "--ozone-platform=wayland"?

### ISSUE THREAD

**Issue by cosme-benito** [cedricroijakkers/linux-windows-deadkeys#1]
First of all, many thanks for this repo. I've been using your `XCompose` for months on X11 and it worked perfectly out of the box. No changes necessary. It's perfect.

I have recently changed to Hyprland, which uses the Wayland and not X11. Overall it works fine but electron apps need `--ozone-platform=wayland` flag to work properly, which makes them ignore the `XCompose` file, unfortunately.

Any way to work around this? Thanks

**Comment by cosme-benito** [comment]
Answering my own question, I found the solution to be `keyd`

- GitHub repo here: https://github.com/rvaiya/keyd

My current `/etc/keyd/default.conf` file:

```conf
[ids]
*

[main]
' = oneshotm(apostrophe, macro(' space))

[apostrophe]
c = macro(backspace G-,)
a = macro(backspace G-a)
e = macro(backspace G-e)
i = macro(backspace G-i)
o = macro(backspace G-o)
u = macro(backspace G-u)
space = macro(space backspace)
```

Don't forget to run `sudo keyd reload` after changing the default.conf file

**Comment by cedricroijakkers** [comment]
For me, `.XCompose` works fine in Wayland, however it is Electron that does not seem to support it. The Electron team seems to ignore the bugs submitted, leave them hanging for 3 months, and then close the issue since they are reported on a no longer supported version of Electron (see https://github.com/electron/electron/issues/29345 and https://github.com/electron/electron/issues/39957). There is also an upstream bug in Chromium itself [here](https://issues.chromium.org/issues/40272818) which is being totally ignored by the Chromium dev team. So, great progress.

**Comment by cosme-benito** [comment]
Yes, that has been my experience as well. Wayland works fine, but not Electron apps. Seems like everyone is shifting blame to everyone else. 

Fortunately `keyd` completely solved my problem, works great under Electron apps as well.
